modelpath = "./modellatest"

HISticker = [["CAACAgIAAxkBAAIFy2E53ViVxBRQLuRjN3W4an4twF6CAAIoAAP3AsgP0HcEB_zEAu8gBA", "\ud83d\ude0a", "EggYolk"],
             ["CAACAgIAAxkBAAIFzWE53WG65AxG5O-cSKJEMksmYNSKAAIsAAP3AsgPvEHgyPvhQNMgBA", "\ud83d\ude03", "EggYolk"],
             ["CAACAgIAAxkBAAIFz2E53Wu-S3Zh-1g3eKMGs0AAAdrLDAACHAAD9wLID3Acci1tkxh4IAQ", "\ud83d\udc4b", "EggYolk"],
             ["CAACAgIAAxkBAAIF0WE53XoDyqLW3xwpvnjF7T6kecslAAJMAQACVp29CncsGQABsZeKuCAE", "\ud83d\ude0e",
              "Halloweenkin"],
             ["CAACAgIAAxkBAAIF02E53XyiwzGP3TimioIpYJjCU8OhAAJAAQACVp29CmzpW0AsSdYlIAQ", "\ud83d\udc4b",
              "Halloweenkin"],
             ["CAACAgIAAxkBAAIF1WE53YxnSD4OUoVxP8ZeIa9fIjgrAAJdAANEDc8Xx77nXM4YAjwgBA", "\ud83d\udc4b", "Orangino"],
             ["CAACAgIAAxkBAAIF12E53ZXWoSa2-gpPsk0zYOJdN8o_AAJIAANEDc8XD04fHOYFeMYgBA", "\ud83d\udc4c", "Orangino"],
             ["CAACAgIAAxkBAAIF2WE53aXlGk2F3Tu3JeR_g6IX99xTAAIuAAMkcWIaiOg2Q2pAQxQgBA", "\ud83d\udc4b", "OwledDidi"],
             ["CAACAgIAAxkBAAIF22E53dK8cI5S6cyjqezB4acO7CQUAAL3AQACFkJrCjn2cG-0Y3_EIAQ", "\ud83d\udc4b", "BobbyTurtle"],
             ["CAACAgIAAxkBAAIF3WE53e6PyiKru1SrBejL9DqDNL3sAAIlAAOymJoODzZ3fI6TwS0gBA", "\ud83d\udc4b", "SweetJam"],
             ["CAACAgIAAxkBAAIF32E53fMx0mRFnwVi5zeCp1JUiB4dAAIgAAOymJoOZIuREzX2MbMgBA", "\ud83e\udd29", "SweetJam"],
             ["CAACAgIAAxkBAAIF4WE53gcHzWp_5uw8xWcY-mvI_N3pAAIaAAOQ_ZoVj-YTCjJewM8gBA", "\ud83d\udc4b", "TheCoffeeCup"],
             ["CAACAgIAAxkBAAIF42E53hpK0djNSrE071B8CH4kaRIRAAIlAAOQ_ZoVOJ3k34nH8QIgBA", "\ud83d\ude0a", "TheCoffeeCup"],
             ["CAACAgIAAxkBAAIF5WE53h_rDZjgaueWXUWCkziA6MGUAAKSAQACVp29Cp_QLQhCLtUFIAQ", "\ud83d\udc4b",
              "DaisyRomashka"],
             ["CAACAgIAAxkBAAIF52E53izSvcVHUGIDM9Ts8HGqeBuHAAJVAgACVp29CqxLLIJPoxXfIAQ", "\ud83d\udc4b", "gldfsh"],
             ["CAACAgIAAxkBAAIF6WE53kJnJdGWMwHgnO0c1Fo__qmZAAKvCwAC_WmBSmHwJMEXoU_EIAQ", "\ud83d\udc4b", "TrickyFox"],
             ["CAACAgIAAxkBAAIF62E53k50QEqCs-wzYsXRQ0rmOp3qAAJPAAOtZbwUa5EcjYesr5MgBA", "\ud83d\udc4b", "DonutTheDog"],
             ["CAACAgIAAxkBAAIF7WE53ls4DgPol2Ejfl61tOWBDKyXAALYDwACSPJgSxX7xNp4dGuYIAQ", "\ud83d\udc4b", "Crocosaurus"],
             ["CAACAgIAAxkBAAIF72E53mjctYoOuJxJZUNNThyxvdO7AAIBAQACVp29CiK-nw64wuY0IAQ", "\ud83d\udc4b", "UtyaDuck"],
             ["CAACAgIAAxkBAAIF8WE53nfCCMoYWWyoxjEV6s_VNptFAAJPAgACVp29Cs_KxolndWWVIAQ",
              "\ud83d\udc6f\u200d\u2640\ufe0f", "UtyaDuck"],
             ["CAACAgIAAxkBAAIF82E53oHZvPWmUfbqTZvHv5xDdTS2AAIFAAPANk8T-WpfmoJrTXUgBA", "\ud83d\udc4b", "HotCherry"]]

deptype = ["Natural Satement", "Study Problems", "Peers Problems", "Relationship Problems", "Loneliness", "Hatered",
           "Work Problems", "Bored", "Unmotivated", "Financial Problems"]



songList = [["https://www.youtube.com/watch?v=WDXPJWIgX-o"],
            ["https://www.youtube.com/watch?v=OLeOfpSv31c", "https://youtu.be/watch?v=mtf7hC17IBM",
             "https://youtu.be/watch?v=X8SHAiI93M0", "https://youtu.be/watch?v=oRtKFh2oglI",
             "https://youtu.be/watch?v=lG-JkvTpsWQ",
             "https://youtu.be/watch?v=_cSRW4S-FkA", "https://youtu.be/watch?v=6QWNbqDwmRM",
             "https://youtu.be/watch?v=BrnDlRmW5hs",
             "https://youtu.be/watch?v=E0Om1LC-XeU", "https://youtu.be/watch?v=Hy7Sk2k8zy8",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=DC2ps4yNxGg", "https://youtu.be/watch?v=h71QGYBlm20",
             "https://youtu.be/watch?v=cnwhoqXLGQw",
             "https://youtu.be/watch?v=VEZ_Ui6d9AM", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=2DzTcLybX8c",
             "https://www.youtube.com/watch?v=lTRiuFIWV54", "https://youtu.be/watch?v=vgx-R_4s12U",
             "https://youtu.be/watch?v=FL9Hcz85CGw", "https://youtu.be/watch?v=jaiqKt9W5uw"],

            ["https://www.youtube.com/watch?v=UIMSetVr4dI", "https://youtu.be/watch?v=IGInsosP0Ac",
             "https://youtu.be/watch?v=fZEsQ13O1Mc", "https://youtu.be/watch?v=JIzlzfogVj4",
             "https://youtu.be/watch?v=vLW1CcbFh18",
             "https://youtu.be/watch?v=e-9aaLDIb_Y", "https://youtu.be/watch?v=ncIPbN3HVqI",
             "https://youtu.be/watch?v=pXRviuL6vMY",
             "https://youtu.be/watch?v=3df83nUZxFk", "https://youtu.be/watch?v=WJXmYwY4WSo",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=V_RJykX0mtA", "https://youtu.be/watch?v=gwUd8Johsvc",
             "https://youtu.be/watch?v=ogARik2FBPk",
             "https://youtu.be/watch?v=NcgEXwjAImo", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=itZ2-EqnqBE",
             "https://www.youtube.com/watch?v=NPJwWE1CAFY", "https://youtu.be/watch?v=dQw4w9WgXcQ",
             "https://youtu.be/watch?v=CyMj_CJG1mE", "https://youtu.be/watch?v=9swhErCrwg0"],
            ["https://www.youtube.com/watch?v=oh2LWWORoiM", "https://youtu.be/watch?v=nijx6Np0o40",
             "https://youtu.be/watch?v=dqqAviWuEnc", "https://youtu.be/watch?v=nDSHtAeDtm0",
             "https://youtu.be/watch?v=ATMJIPqRrc4",
             "https://youtu.be/watch?v=cRi-x2r88no", "https://youtu.be/watch?v=T_lC2O1oIew",
             "https://youtu.be/watch?v=osdoLjUNFnA",
             "https://youtu.be/watch?v=PxN6X6FevFw", "https://youtu.be/watch?v=RirtNDMfWJk",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=QgaTQ5-XfMM", "https://youtu.be/watch?v=c8rq4uIeL20",
             "https://youtu.be/watch?v=alvAtuHzAlc",
             "https://youtu.be/watch?v=wPt0dGg4BKA", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=_4ce7K0e2DM",
             "https://www.youtube.com/watch?v=i0DCGOx13iM", "https://youtu.be/watch?v=4nZ7KkJ_JMo",
             "https://youtu.be/watch?v=4G4tntY30Qw ", "https://youtu.be/watch?v=E0RC8TeLbGY"],
            ["https://www.youtube.com/watch?v=8-YvO-yKaf8", "https://youtu.be/watch?v=sElE_BfQ67s",
             "https://youtu.be/watch?v=VEyJydN0y1g", "https://youtu.be/watch?v=_OuGRiAdiuc",
             "https://youtu.be/watch?v=bhR5O5ve5Hs",
             "https://youtu.be/watch?v=xQOO2xGQ1Pc", "https://youtu.be/watch?v=iIuuMNbSjDE",
             "https://youtu.be/watch?v=gnVC7WxbJI0",
             "https://youtu.be/watch?v=zwRjkD4lYJs", "https://youtu.be/watch?v=cVF1kz5Mn6c",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=zMvCfm_AjYo", "https://youtu.be/watch?v=WO8bAhDZvOE",
             "https://youtu.be/watch?v=o5Fs6NSDWMk",
             "https://youtu.be/watch?v=UVzQ8T75yhM", "https://youtu.be/watch?v=kAIyPrN5jBc",
             "https://youtu.be/watch?v=TQVuqYklp6w",
             "https://www.youtube.com/watch?v=jATVgJ_grys", "https://youtu.be/watch?v=uuodbSVO3z0",
             "https://youtu.be/watch?v=0s1dTAq091Y", "https://youtu.be/watch?v=Xo8i04qCMek"],
            ["https://www.youtube.com/watch?v=ZAfAud_M_mg&list=RDoh2LWWORoiM&index=7",
             "https://youtu.be/watch?v=hLf6yZPJyvM",
             "https://youtu.be/watch?v=p4Vv0hyoXZ4", "https://youtu.be/watch?v=ALj5MKjy2BU",
             "https://youtu.be/watch?v=ZQFmRXgeR-s",
             "https://youtu.be/watch?v=UgZ8WTOOUe8", "https://youtu.be/watch?v=IhSPyR72CqM",
             "https://youtu.be/watch?v=NaFd8ucHLuo",
             "https://youtu.be/watch?v=jmu0qkNzFSM", "https://youtu.be/watch?v=pqMkDB1fwfY",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=ntrTDKAChZU", "https://youtu.be/watch?v=YOkM-ZPz7XY",
             "https://youtu.be/watch?v=mFoFRRs9P3g",
             "https://youtu.be/watch?v=Q_dqfcvTZik", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=UlNuaUHcv-A",
             "https://www.youtube.com/watch?v=Lju6h-C37hE&t=10002s", "https://youtu.be/watch?v=U3ASj1L6_sY",
             "https://youtu.be/watch?v=X1-FlWbvYRk. ", "https://youtu.be/watch?v=juuxZ00rNEs"],
            ["https://www.youtube.com/watch?v=xH7zsRXS9vM", "https://youtu.be/watch?v=R88PFD6prq0",
             "https://youtu.be/watch?v=R7yYi6ft8sU", "https://youtu.be/watch?v=Psr7yfO_WY0",
             "https://youtu.be/watch?v=OYuRPH17pLs",
             "https://youtu.be/watch?v=HL1UzIK-flA", "https://youtu.be/watch?v=AZPTDy9oPO4",
             "https://youtu.be/watch?v=JdSpuTi9d8A",
             "https://youtu.be/watch?v=pdYJtRBPlTw", "https://youtu.be/watch?v=pqMkDB1fwfY",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=q3YJe63kNWE", "https://youtu.be/watch?v=-sCEfhaLYwY",
             "https://youtu.be/watch?v=nJF5GzMjh6c",
             "https://youtu.be/watch?v=9cNQFB0TDfY", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=SMRlqaS2Hyk",
             "https://www.youtube.com/watch?v=5-ndIMxN9Ys", "https://youtu.be/watch?v=Y1xs_xPb46M",
             "https://youtu.be/watch?v=8Wk2dJD-U8I", "https://youtu.be/watch?v=DQcwuBlrOqY"],
            ["https://www.youtube.com/watch?v=xH7zsRXS9vM", "https://youtu.be/watch?v=R88PFD6prq0",
             "https://youtu.be/watch?v=R7yYi6ft8sU", "https://youtu.be/watch?v=Psr7yfO_WY0",
             "https://youtu.be/watch?v=OYuRPH17pLs",
             "https://youtu.be/watch?v=HL1UzIK-flA", "https://youtu.be/watch?v=AZPTDy9oPO4",
             "https://youtu.be/watch?v=JdSpuTi9d8A",
             "https://youtu.be/watch?v=pdYJtRBPlTw", "https://youtu.be/watch?v=pqMkDB1fwfY",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=q3YJe63kNWE", "https://youtu.be/watch?v=-sCEfhaLYwY",
             "https://youtu.be/watch?v=nJF5GzMjh6c",
             "https://youtu.be/watch?v=9cNQFB0TDfY", "https://youtu.be/watch?v=1CTuqWal9nk",
             "https://youtu.be/watch?v=SMRlqaS2https://www.youtube.com/watch?v=5aw8CD9AdOY",
             "https://youtu.be/watch?v=LYSUnj615Iw",
             "https://youtu.be/watch?v=plrKsxgi4xg", "https://youtu.be/watch?v=Sv6dMFF_yts",
             "https://youtu.be/watch?v=gADgM89skZQ",
             "https://youtu.be/watch?v=dqqAviWuEnc", "https://youtu.be/watch?v=fug816ocVqs",
             "https://youtu.be/watch?v=xVf4Zk8CBj0",
             "https://youtu.be/watch?v=68Eu4-Dz-MA", "https://youtu.be/watch?v=L-J09dN5m9Y",
             "https://youtu.be/watch?v=gHWlP-AimsY",
             "https://youtu.be/watch?v=9odmbJMqAgk", "https://youtu.be/watch?v=UNL3LdkqXCg",
             "https://youtu.be/watch?v=_kAcPcDv-S4",
             "https://youtu.be/watch?v=l67YBII_e4Y", "https://www.youtube.com/watch?v=GnoA4ZGEHXY",
             "https://youtu.be/watch?v=JPIhUaONiLU", "https://youtu.be/watch?v=02Hct4xaNfA ",
             "https://youtu.be/watch?v=qe6DGapE_Y8Hyk",
             "https://www.youtube.com/watch?v=5-ndIMxN9Ys", "https://youtu.be/watch?v=Y1xs_xPb46M",
             "https://youtu.be/watch?v=8Wk2dJD-U8I", "https://youtu.be/watch?v=DQcwuBlrOqY"],
            ["https://www.youtube.com/watch?v=5aw8CD9AdOY", "https://youtu.be/LYSUnj615Iw",
             "https://youtu.be/watch?v=plrKsxgi4xg", "https://youtu.be/watch?v=Sv6dMFF_yts",
             "https://youtu.be/watch?v=OYuRPH17pLs",
             "https://youtu.be/watch?v=gADgM89skZQ", "https://youtu.be/watch?v=dqqAviWuEnc",
             "https://youtu.be/watch?v=fug816ocVqs",
             "https://youtu.be/watch?v=xVf4Zk8CBj0", "https://youtu.be/watch?v=68Eu4-Dz-MA",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=L-J09dN5m9Y", "https://youtu.be/watch?v=gHWlP-AimsY",
             "https://youtu.be/watch?v=9odmbJMqAgk",
             "https://youtu.be/watch?v=UNL3LdkqXCg", "https://youtu.be/watch?v=_kAcPcDv-S4",
             "https://youtu.be/watch?v=l67YBII_e4Y",
             "https://www.youtube.com/watch?v=GnoA4ZGEHXY", "https://youtu.be/watch?v=JPIhUaONiLU",
             "https://youtu.be/watch?v=02Hct4xaNfA ", "https://youtu.be/watch?v=qe6DGapE_Y8"],
            ["https://www.youtube.com/watch?v=v-PZoTZmgu4", "https://youtu.be/watch?v=9bdLTPNrlEg",
             "https://youtu.be/watch?v=DhHGDOgjie4", "https://youtu.be/watch?v=VMqDSntAbC0",
             "https://youtu.be/watch?v=aN_EvIKPxrE",
             "https://youtu.be/watch?v=g6BtbIiJ_rc", "https://youtu.be/watch?v=n7cDP6pqNkw",
             "https://youtu.be/watch?v=kJtYLPJpDbo",
             "https://youtu.be/watch?v=8Th4BWkfFDE", "https://youtu.be/watch?v=Hy7Sk2k8zy8",
             "https://youtu.be/watch?v=IvrSQGIOpMY",
             "https://youtu.be/watch?v=7maJOI3QMu0 ", "https://youtu.be/watch?v=g4uDXDMlsxE",
             "https://youtu.be/watch?v=GgwUenaQqlM",
             "https://youtu.be/watch?v=u5CVsCnxyXg", "https://youtu.be/watch?v=kAIyPrN5jBc",
             "https://youtu.be/watch?v=g94DBEV1kVA",
             "https://www.youtube.com/watch?v=5VbVP13TciI", "https://youtu.be/watch?v=B3toakBtrMY",
             "https://youtu.be/watch?v=Emh3Ca2B1WM", "https://youtu.be/watch?v=ZmfQP1JOcaM"]
            ]


